on:
  push:
     branches:
       - master

name: bookdown

jobs:

  bookdown:

    if: "!contains(github.event.head_commit.message, 'skip deploy')"

    name: Render-Book

    runs-on: ubuntu-16.04

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: "https://packagemanager.rstudio.com/cran/__linux__/xenial/latest"

    steps:

      - uses: actions/checkout@v1

      - uses: r-lib/actions/setup-r@v1

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Install tinytex
        uses: r-lib/actions/setup-tinytex@master

      - name: Install CRAN packages
        run: Rscript -e 'install.packages(c("rmarkdown", "bookdown", "remotes", "evabic"), Ncpus = 4)'

      - name: Install GitHub packages
        run: Rscript -e 'remotes::install_github(c("ismayc/thesisdown", "abichat/zazou"), Ncpus = 4)'

      - name: Render Book
        run: Rscript -e 'bookdown::render_book("index.Rmd", c("thesisdown::thesis_pdf", "thesisdown::thesis_gitbook")); warnings()'

      - uses: actions/upload-artifact@v1
        with:
          name: _book
          path: _book/

# Need to first create an empty gh-pages branch
# see https://pkgdown.r-lib.org/reference/deploy_site_github.html
# and also add secrets for a GHTOKEN and EMAIL to the repository
# gh-action from Cecilapp/GitHub-Pages-deploy
  checkout-and-deploy:

    if: "!contains(github.event.head_commit.message, 'skip deploy')"

    runs-on: ubuntu-latest
    needs: bookdown

    steps:

     - name: Checkout
       uses: actions/checkout@master

     - name: Download artifact
       uses: actions/download-artifact@v1.0.0
       with:
         # Artifact name
         name: _book # optional
         # Destination path
         path: _book # optional

     - name: Deploy to GitHub Pages
       uses: Cecilapp/GitHub-Pages-deploy@master
       env:
          EMAIL: ${{ secrets.EMAIL }}               # must be a verified email
          GH_TOKEN: ${{ secrets.GHTOKEN }} # https://github.com/settings/tokens
          BUILD_DIR: _book/                     # "_site/" by default
